name: Validate JSONs

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: OrRosenbaltt/validate-json-action@0.1.0
        env:
          INPUT_SCHEMA: /updateLists/verify.schema.json
          INPUT_JSONS: /*.json,/updateLists/playerlist.milenko-cumulative.json
